# Generated by Django 4.1.4 on 2022-12-23 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ]
                    ),
                ),
                (
                    "period",
                    models.IntegerField(choices=[("1", "Autumn"), ("2", "Spring")]),
                ),
            ],
            options={
                "unique_together": {("year", "period")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("roll_number", models.CharField(max_length=10, unique=True)),
                ("date_of_birth", models.DateField()),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "cgpa",
                    models.DecimalField(decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "acgpa",
                    models.DecimalField(decimal_places=2, max_digits=4, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("credits", models.IntegerField()),
                ("lectures", models.IntegerField()),
                ("tutorials", models.IntegerField()),
                ("practicals", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_type", models.CharField(max_length=32)),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (10, "Ex"),
                            (9, "A"),
                            (8, "B"),
                            (7, "C"),
                            (6, "D"),
                            (5, "P"),
                            (0, "F"),
                            (-1, "U"),
                        ]
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.semester"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.student"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.subject"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentSemester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("sgpa", models.DecimalField(decimal_places=2, max_digits=4)),
                ("asgpa", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.semester"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.student"
                    ),
                ),
            ],
        ),
    ]
