# Generated by Django 4.1.4 on 2022-12-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
