# Generated by Django 4.1.4 on 2022-12-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_student_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsemester",
            name="acgpa",
            field=models.DecimalField(decimal_places=2, default=1.23, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="addn_credits_cleared",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="addn_credits_taken",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="addn_total_credits_cleared",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="addn_total_credits_taken",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="cgpa",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="credits_cleared",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="credits_taken",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="ncgpa",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="total_credits_cleared",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentsemester",
            name="total_credits_taken",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
