# Generated by Django 4.1.4 on 2022-12-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_subject_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="period",
            field=models.IntegerField(choices=[(1, "Autumn"), (2, "Spring")]),
        ),
        migrations.AlterField(
            model_name="studentsubject",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.studentsemester"
            ),
        ),
    ]
