# Generated by Django 4.1.4 on 2022-12-23 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_semester_period_alter_studentsubject_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsubject",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="core.studentsemester",
            ),
        ),
    ]
