# Generated by Django 4.1.4 on 2022-12-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_student_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
