# Generated by Django 4.1.4 on 2022-12-24 10:46

import django.core.validators
from django.db import migrations, models


def set_default(apps, schema_editor):
    Student = apps.get_model("core", "Student")
    for student in Student.objects.all().iterator():
        student.year_enrolled = 2000 + int(student.roll_number[:2])
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_student_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="year_enrolled",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.RunPython(set_default, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="student",
            name="year_enrolled",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
