# Generated by Django 4.1.4 on 2022-12-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_student_year_enrolled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="period",
            field=models.IntegerField(choices=[(1, "Spring"), (2, "Autumn")]),
        ),
    ]
